stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - config/paths_config.py
    outs:
      - artifacts/ingested_data

  data_processing:
    cmd: python src/data_processing.py
    deps:
      - src/data_processing.py
      - config/paths_config.py
    outs:
      - artifacts/processed_data

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - config/paths_config.py
      - utils/helpers.py
    outs:
      - artifacts/engineered_data

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - config/paths_config.py
    outs:
      - artifacts/models